[[stack]]
name = "tsdproxy"
tags = ["tsdproxy"]
[stack.config]
server = "localhost"
links = [
  "https://komodo.shark-perch.ts.net/resource-syncs/682c2da31fdb036196a27889"
]
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "b-"
repo = "b-/tsdproxy-deploy"

##

[[resource_sync]]
name = "tsdproxy-deploy"
tags = ["tsdproxy"]
[resource_sync.config]
repo = "b-/tsdproxy-deploy"
git_account = "b-"
resource_path = ["stack.toml"]
managed = true
match_tags = ["tsdproxy"]